apiVersion: v1
data:
  game.properties: |-
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-21T20:24:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:game.properties: {}
        f:ui.properties: {}
    manager: kubectl.exe
    operation: Update
    time: "2020-07-21T20:24:16Z"
  name: game-config
  namespace: default
  resourceVersion: "1013"
  selfLink: /api/v1/namespaces/default/configmaps/game-config
  uid: 54a8cf97-e483-42fc-b41e-8b33e01ef6d0